- id: lint-modules
  name: Lint nf-core modules
  # description: This hook trims trailing whitespace.
  entry: nf-core --hide-progress modules lint
  language: python
  types: [text]
  files: ^modules/.*/.*/.*\.nf$
  pass_filenames: true
  # args: []
  # NOTE See https://github.com/nf-core/modules/pull/7084 for reasoning
- id: lint-subworkflows
  name: Lint nf-core subworkflows
  description: Runs linting on all the subworkflows
  entry: nf-core --hide-progress subworkflows lint -a
  language: python
  types: [text]
  files: ^subworkflows/[^/]+$
  alias: sw
  pass_filenames: false
  # args: []
- id: lint-pipeline
  name: Lint nf-core pipeline
  description: Check pipeline code against nf-core guidelines.
  entry: nf-core --hide-progress lint
  language: python
  types: [text]
  # args: []
