name: Update Modules Template

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update_modules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: dev

      - name: Set up Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5
        with:
          python-version: "3.x"

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: "24.04.2"

      - name: Install nf-core
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Update modules
        run: nf-core modules update --all --no-preview
        working-directory: nf_core/pipeline-template

      - name: Update subworkflows
        run: nf-core subworkflows update --all --no-preview
        working-directory: nf_core/pipeline-template

      # Commit the changes
      - name: Commit changes
        run: |
          git config user.email "core@nf-co.re"
          git config user.name "nf-core-bot"
          git add .
          git status
          git commit -m "[automated] Update components in template"

      # Open a new PR to dev with the changes
      - name: Create PR
        run: |
          git checkout -b update-modules
          git push origin update-modules
          gh pr create --title "Template: Update components in template" --body "This PR updates the modules and subworkflows in the pipeline template" --base dev --head update-modules
